"""Functional form of the 3D transforms in :mod:`vision3d.transforms`."""

from ._camera import (
    center_crop_camera_intrinsics,
    crop_camera_intrinsics,
    horizontal_flip_camera_extrinsics,
    horizontal_flip_camera_intrinsics,
    pad_camera_intrinsics,
    resize_camera_intrinsics,
    resized_crop_camera_intrinsics,
    vertical_flip_camera_extrinsics,
    vertical_flip_camera_intrinsics,
)
from ._geometry import (
    flip_3d,
    flip_3d_bounding_boxes,
    flip_3d_point_cloud,
    horizontal_flip_bounding_boxes_3d,
    horizontal_flip_point_cloud_3d,
    rotate_3d,
    rotate_3d_bounding_boxes,
    rotate_3d_camera_extrinsics,
    rotate_3d_point_cloud,
    scale_3d,
    scale_3d_bounding_boxes,
    scale_3d_camera_extrinsics,
    scale_3d_point_cloud,
    translate_3d,
    translate_3d_bounding_boxes,
    translate_3d_camera_extrinsics,
    translate_3d_point_cloud,
    vertical_flip_bounding_boxes_3d,
    vertical_flip_point_cloud_3d,
)
from ._point_cloud import (
    jitter_points,
    jitter_points_point_cloud,
    sample_points,
    sample_points_point_cloud,
    shuffle_points,
    shuffle_points_point_cloud,
)
from ._registry import register_kernel

__all__ = [
    "center_crop_camera_intrinsics",
    "crop_camera_intrinsics",
    "flip_3d",
    "flip_3d_bounding_boxes",
    "flip_3d_point_cloud",
    "horizontal_flip_bounding_boxes_3d",
    "horizontal_flip_camera_extrinsics",
    "horizontal_flip_camera_intrinsics",
    "horizontal_flip_point_cloud_3d",
    "jitter_points",
    "jitter_points_point_cloud",
    "pad_camera_intrinsics",
    "register_kernel",
    "resize_camera_intrinsics",
    "resized_crop_camera_intrinsics",
    "rotate_3d",
    "rotate_3d_bounding_boxes",
    "rotate_3d_camera_extrinsics",
    "rotate_3d_point_cloud",
    "sample_points",
    "sample_points_point_cloud",
    "scale_3d",
    "scale_3d_bounding_boxes",
    "scale_3d_camera_extrinsics",
    "scale_3d_point_cloud",
    "shuffle_points",
    "shuffle_points_point_cloud",
    "translate_3d",
    "translate_3d_bounding_boxes",
    "translate_3d_camera_extrinsics",
    "translate_3d_point_cloud",
    "vertical_flip_bounding_boxes_3d",
    "vertical_flip_camera_extrinsics",
    "vertical_flip_camera_intrinsics",
    "vertical_flip_point_cloud_3d",
]
