name: test

on:
  workflow_call:
    inputs:
      cache:
        description: "Whether the build should be cached."
        type: boolean
        default: true

permissions: {}

jobs:
  test:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - name: Install system dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y --no-install-recommends \
            libgl1 \
            libglib2.0-0 \
            libsm6 \
            libxcb1 \
            libxext6 \
            libxrender1 \
            ninja-build
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false
      - name: Set up uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8
        with:
          python-version: "3.14"
          enable-cache: ${{ inputs.cache }}
          cache-local-path: ${{ github.workspace }}/.uv-cache
          cache-suffix: test-cpu
      - name: Install project
        run: uv sync --locked --all-extras
      - name: Run CPU tests
        run: uv run pytest -m cpu
